### ISSUE TITLE
Longjohn error with Titanium CLI (OSS version)

### ISSUE THREAD

**Issue by cmayo** [appcelerator/titanium#229] opened 2015-08-03 09:17 UTC
Hello, i'm using the open source versión of Appcelerator Titanium. I've followed this tutorial (https://github.com/m1ga/titanium_with_atom/blob/master/README.md) and installed those node packages: titanium, tisdk and alloy. I've installed the last Titanium SDK (4.1.0.GA).

My problem is when i do a "ti info" or a "ti build -p ...." i allways get this error:

    //usr/local/lib/node_modules/titanium/node_modules/longjohn/dist/longjohn.js:195
    throw e;
          ^
    Error: spawn EACCES
    at exports._errnoException (util.js:746:11)

My node versión is v0.12.7.

I've followed this workaround (https://community.appcelerator.com/topic/937/longjohn-js-throw-e-when-running-titanium-cli) and i've downgrade the longjohn version to 0.2.4 but now i get this error related with the same longjohn package:

     //usr/local/lib/node_modules/titanium/node_modules/longjohn/dist/longjohn.js:185
    throw e;
          ^
    ChildProcess.emit (events.js:110:17),maybeClose (child_process.js:1015:16),Socket.<anonymous> (child_process.js:1183:11),Socket.emit (events.js:107:17),Pipe.close (net.js:485:12)

Does anyone know how to resolve this issue? I can't develop anything with Titanium now.

**Comment by cb1kenobi** [comment] 2015-08-03 14:16
There are a million things that can cause a Longjohn error. If I had to guess, the problem is the Titanium CLI is trying to execute another executable that is not executable. Which executable is the problem? No idea because you didn't paste the full stack trace.

Another community user notice the file `~/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/node_modules/ioslib/lib/ios-sim` was not executable, so maybe you have the same problem? You simply need to `chmod +x <PATH>`. If this file is already executable, then it's some other executable that is the problem.

**Comment by cmayo** [comment] 2015-08-04 21:53
Hello, with `chmod +x ~/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/node_modules/ioslib/lib/ios-sim` i have resolve all errors.

Thanks

**Comment by cb1kenobi** [comment] 2015-08-04 21:54
@cmayo Awesome! Closing ticket. Thank you!

**Closed by cb1kenobi** 2015-08-04 21:54 UTC

**Comment by sfeather** [comment] 2015-08-04 21:59
If you used the tisdk utility  prior to version 1.2.2, that might be the source of your permissions problems.
ios-sim will not be your only problem, as thats not the only executable within the SDK.

Suggest removing the sdk, update tisdk (if thats your source) and redownload the sdk to be sure all of the executable files have the correct flags.

**Comment by cmayo** [comment] 2015-08-05 06:57
@sfeather thanks, i had tisdk version 1.1.0. With updating tisdk and redownloading the sdk i also have fixed this error.
