### ISSUE TITLE
(node) sys is deprecated. Use util instead.

### ISSUE THREAD

**Issue by DouglasHennrich** [appcelerator/titanium#237] opened 2015-12-14 05:12 UTC
`node -v 4.2.2`
`ti -v 5.0.5`

**Comment by cb1kenobi** [comment] 2015-12-14 11:21
@DouglasHennrich The Titanium CLI doesn't use "sys". Can you provide me with some details as to why you think we use the "sys" module?

**Comment by DouglasHennrich** [comment] 2015-12-14 15:29
I just run `ti clean -p android` and it shows.
```
ti clean -p android
(node) sys is deprecated. Use util instead.
Titanium Command-Line Interface, CLI version 5.0.5, Titanium SDK version 5.1.1.GA
Copyright (c) 2012-2015, Appcelerator, Inc.  All Rights Reserved.

Please report bugs to http://jira.appcelerator.org/

[DEBUG] Detecting plugins in /Users/Odin/Documents/Projects/Prezzo/plugins
[DEBUG] Detected plugin: ti.alloy @ /Users/Odin/Documents/Projects/Prezzo/plugins/ti.alloy
[DEBUG] Looking for Titanium plugin id=ti.alloy version=1.0
[INFO]  Found Titanium plugin id=ti.alloy version=1.0 
[DEBUG] Directory does not exist /Users/Odin/Documents/Projects/Prezzo/build/android
[DEBUG] Build log does not exist /Users/Odin/Documents/Projects/Prezzo/build/build_android.log
[DEBUG] Resources directory of /Users/Odin/Documents/Projects/Prezzo/app has been emptied
```

**Comment by cb1kenobi** [comment] 2015-12-14 16:54
That's strange. I searched all of the Titanium CLI, Titanium SDK, and Alloy tooling code and we do not use the "sys" module. Furthermore, I cannot reproduce it with Node.js 4.2.3 or 5.2.0.

Maybe you have a 3rd party Titanium CLI plugin installed?

**Comment by DouglasHennrich** [comment] 2015-12-14 17:44
```
[3:43:50] Prezzo git:(v1.0.0) ✗ ti plugin
(node) sys is deprecated. Use util instead.
Titanium Command-Line Interface, CLI version 5.0.5, Titanium SDK version 5.1.1.GA
Copyright (c) 2012-2015, Appcelerator, Inc.  All Rights Reserved.

Please report bugs to http://jira.appcelerator.org/

Project CLI Plugins
ti.alloy
  Version    = unknown
  Location   = /Users/Odin/Documents/Projects/Prezzo/plugins/ti.alloy
  Commands   = No commands found
  Hooks      = alloy (v1.0.0)
               deepclean
 
Configured Path CLI Plugins
No CLI plugins found
 
Global CLI Plugins
No CLI plugins found
```

I have downloaded `TiShadow` maybe this is the problem? Don't know why

**Comment by cb1kenobi** [comment] 2015-12-14 18:48
Hmm, I did a quick grep on TiShadow and didn't see it using the "sys" module either.

Since there doesn't appear to be an issue with the stable release, I'm going to close this ticket. If you feel like further investigating, I would be curious what the culprit is.

**Closed by cb1kenobi** 2015-12-14 18:48 UTC

**Comment by DouglasHennrich** [comment] 2015-12-22 14:47
@cb1kenobi 
Found the problem... it's `tishadow` it override something on `titanium-cli`

**Comment by cb1kenobi** [comment] 2015-12-22 17:04
I see it now. TiShadow uses a dependency "tiapp" which is out-of-date: https://github.com/dbankier/TiShadow/blob/master/package.json#L25. The version should be bumped to `0.0.3`. I submitted a PR to TiShadow: https://github.com/dbankier/TiShadow/pull/472.

**Comment by DouglasHennrich** [comment] 2015-12-22 17:28
:+1:  Thanks @cb1kenobi

**Comment by cb1kenobi** [comment] 2015-12-22 21:21
@DouglasHennrich TiShadow v2.8.5 is published! https://www.npmjs.com/package/tishadow

**Comment by DouglasHennrich** [comment] 2015-12-22 23:44
Thanks again @cb1kenobi ! :D
